let {
    addDef, enumeration
} = require('../helpers');

module.exports = () => {
    addDef('ActorValueEnum', 
        enumeration({
            0: 'Aggresion',
            1: 'Confidence',
            2: 'Energy',
            3: 'Responsibility',
            4: 'Mood',
            5: 'Strength',
            6: 'Perception',
            7: 'Endurance',
            8: 'Charisma',
            9: 'Intelligence',
            10: 'Agility',
            11: 'Luck',
            12: 'Action Points',
            13: 'Carry Weight',
            14: 'Critical Chance',
            15: 'Heal Rate',
            16: 'Health',
            17: 'Melee Damage',
            18: 'Damage Resistance',
            19: 'Poison Resistance',
            20: 'Rad Resistance',
            21: 'Speed Multiplier',
            22: 'Fatigue',
            23: 'Karma',
            24: 'XP',
            25: 'Perception Condition',
            26: 'Endurance Condition',
            27: 'Left Attack Condition',
            28: 'Right Attack Condition',
            29: 'Left Mobility Condition',
            30: 'Right Mobility Condition',
            31: 'Brain Condition',
            32: 'Barter',
            33: 'Big Guns',
            34: 'Energy Weapons',
            35: 'Explosives',
            36: 'Lockpick',
            37: 'Medicine',
            38: 'Melee Weapons',
            39: 'Repair',
            40: 'Science',
            41: 'Small Guns',
            42: 'Sneak',
            43: 'Speech',
            44: 'Throwing (unused)',
            45: 'Unarmed',
            46: 'Inventory Weight',
            47: 'Paralysis',
            48: 'Invisibility',
            49: 'Chameleon',
            50: 'Night Eye',
            51: 'Detect Life Range',
            52: 'Fire Resistance',
            53: 'Water Breathing',
            54: 'Rad Level',
            55: 'Bloody Mess',
            56: 'Unarmed Damage',
            57: 'Assistance',
            58: 'Electric Resistance',
            59: 'Frost Resistance',
            60: 'Energy Resistance',
            61: 'EMP Resistance',
            62: 'Variable01',
            63: 'Variable02',
            64: 'Variable03',
            65: 'Variable04',
            66: 'Variable05',
            67: 'Variable06',
            68: 'Variable07',
            69: 'Variable08',
            70: 'Variable09',
            71: 'Variable10',
            72: 'Ignore Negative Effects',
            "-1": 'None'
        })
    );
};