let {
    addDef, multiStruct, subrecord, struct, uint8, 
    bytes, union, float, ckFormId, uint16, 
    int32, enum32, ref, enumS32, uint32, 
    formId, zstring
} = require('../helpers');

module.exports = () => {
    addDef('CTDA', 
        multiStruct('Condition', [
            subrecord('CTDA', struct('', [
                uint8('Type'),
                bytes('Unused', 3),,
                union('Comparison Value', 'CTDACompValueDecider', [
                    float('Comparison Value - Float'),
                    ckFormId('Comparison Value - Global', ['GLOB']),
                ]),
                uint16('Function'),
                bytes('Unused', 2),,
                union('Parameter #1', 'CTDAParam1Decider', [
                    bytes('Unknown', 4),,
                    bytes('None', 4),,
                    int32('Integer'),
                    float('Float'),
                    bytes('Variable Name (unused)', 4),,
                    enum32('Sex', ref('SexEnum')),
                    enumS32('Actor Value', ref('ActorValueEnum')),
                    enum32('Crime Type', ref('CrimeTypeEnum')),
                    enum32('Axis', ref('AxisEnum')),
                    int32('Quest Stage (unused)'),
                    enum32('Misc Stat', ref('MiscStatEnum')),
                    enum32('Alignment', ref('AlignmentEnum')),
                    ckFormId('Equip Type', ['EQUP']),
                    enum32('Form Type', ref('FormTypeEnum')),
                    enum32('Critical Stage', ref('CriticalStageEnum')),
                    ckFormId('Object Reference', ['NULL', 'PLYR', 'ACHR', 'REFR', 'PGRE', 'PHZD', 'PMIS', 'PARW', 'PBAR', 'PBEA', 'PCON', 'PFLA']),
                    ckFormId('Inventory Object', ['ARMO', 'BOOK', 'MISC', 'WEAP', 'AMMO', 'KEYM', 'ALCH', 'SCRL', 'SLGM', 'INGR', 'FLST', 'LIGH', 'LVLI', 'COBJ']),
                    ckFormId('Actor', ['NULL', 'PLYR', 'ACHR', 'REFR']),
                    ckFormId('Voice Type', ['VTYP', 'FLST']),
                    ckFormId('Idle', ['IDLE']),
                    ckFormId('Form List', ['FLST']),
                    ckFormId('Quest', ['QUST']),
                    ckFormId('Faction', ['FACT']),
                    ckFormId('Cell', ['CELL']),
                    ckFormId('Class', ['CLAS']),
                    ckFormId('Race', ['RACE']),
                    ckFormId('Actor Base', ['NPC_']),
                    ckFormId('Global', ['GLOB']),
                    ckFormId('Weather', ['WTHR']),
                    ckFormId('Package', ['PACK']),
                    ckFormId('Encounter Zone', ['ECZN']),
                    ckFormId('Perk', ['PERK']),
                    ckFormId('Owner', ['NULL', 'FACT', 'NPC_']),
                    ckFormId('Furniture', ['FURN', 'FLST']),
                    ckFormId('Effect Item', ['SPEL', 'ENCH', 'ALCH', 'INGR', 'SCRL']),
                    ckFormId('Base Effect', ['MGEF']),
                    ckFormId('Worldspace', ['WRLD', 'FLST']),
                    enum32('VATS Value Function', ref('VATSValueFunctionEnum')),
                    uint32('VATS Value Param (INVALID)'),
                    ckFormId('Referenceable Object', ['NULL', 'NPC_', 'PROJ', 'TREE', 'SOUN', 'ACTI', 'DOOR', 'STAT', 'FURN', 'CONT', 'ARMO', 'AMMO', 'MISC', 'WEAP', 'BOOK', 'KEYM', 'ALCH', 'LIGH', 'GRAS', 'ASPC', 'IDLM', 'ARMA', 'MSTT', 'TACT', 'FLST', 'LVLI', 'LVSP', 'SPEL', 'SCRL', 'SHOU', 'SLGM', 'ENCH']),
                    ckFormId('Region', ['REGN']),
                    ckFormId('Keyword', ['KYWD', 'NULL']),
                    enum32('Player Action', ref('AdvanceActionEnum')),
                    enum32('Casting Type', ref('CastingSourceEnum')),
                    ckFormId('Shout', ['SHOU']),
                    ckFormId('Location', ['LCTN']),
                    ckFormId('Location Ref Type', ['LCRT']),
                    int32('Alias'),
                    uint32('Packdata ID'),
                    ckFormId('Association Type', ['ASTP']),
                    enum32('Furniture Anim', ref('FurnitureAnimTypeEnum')),
                    enum32('Furniture Entry', [
                        {
                            '0x010000': 'Front',
                            '0x020000': 'Behind',
                            '0x040000': 'Right',
                            '0x80000': 'Left',
                            '0x100000': 'Up',
                        }
                    ]),
                    ckFormId('Scene', ['NULL', 'SCEN']),
                    enum32('Ward State', ref('WardStateEnum')),
                    uint32('Event'),
                    formId('Event Data'),
                ]),
                union('Parameter #2', 'CTDAParam2Decider', [
                    bytes('Unknown', 4),,
                    bytes('None', 4),,
                    int32('Integer'),
                    float('Float'),
                    bytes('Variable Name (unused)', 4),,
                    enum32('Sex', ref('SexEnum')),
                    enumS32('Actor Value', ref('ActorValueEnum')),
                    enum32('Crime Type', ref('CrimeTypeEnum')),
                    enum32('Axis', ref('AxisEnum')),
                    int32('Quest Stage'),
                    enum32('Misc Stat', ref('MiscStatEnum')),
                    enum32('Alignment', ref('AlignmentEnum')),
                    ckFormId('Equip Type', ['EQUP']),
                    enum32('Form Type', ref('FormTypeEnum')),
                    enum32('Critical Stage', ref('CriticalStageEnum')),
                    ckFormId('Object Reference', ['NULL', 'PLYR', 'ACHR', 'REFR', 'PGRE', 'PHZD', 'PMIS', 'PARW', 'PBAR', 'PBEA', 'PCON', 'PFLA']),
                    ckFormId('Inventory Object', ['ARMO', 'BOOK', 'MISC', 'WEAP', 'AMMO', 'KEYM', 'ALCH', 'SCRL', 'SLGM', 'INGR', 'FLST', 'LIGH', 'LVLI', 'COBJ']),
                    ckFormId('Actor', ['NULL', 'PLYR', 'ACHR', 'REFR']),
                    ckFormId('Voice Type', ['VTYP', 'FLST']),
                    ckFormId('Idle', ['IDLE']),
                    ckFormId('Form List', ['FLST']),
                    ckFormId('Quest', ['QUST']),
                    ckFormId('Faction', ['FACT']),
                    ckFormId('Cell', ['CELL']),
                    ckFormId('Class', ['CLAS']),
                    ckFormId('Race', ['RACE']),
                    ckFormId('Actor Base', ['NPC_']),
                    ckFormId('Global', ['GLOB']),
                    ckFormId('Weather', ['WTHR']),
                    ckFormId('Package', ['PACK']),
                    ckFormId('Encounter Zone', ['ECZN']),
                    ckFormId('Perk', ['PERK']),
                    ckFormId('Owner', ['NULL', 'FACT', 'NPC_']),
                    ckFormId('Furniture', ['FURN', 'FLST']),
                    ckFormId('Effect Item', ['SPEL', 'ENCH', 'ALCH', 'INGR', 'SCRL']),
                    ckFormId('Base Effect', ['MGEF']),
                    ckFormId('Worldspace', ['WRLD', 'FLST']),
                    enum32('VATS Value Function', ref('VATSValueFunctionEnum')),
                    union('VATS Value Param', 'CTDAParam2VATSValueParamDecider', [
                        ckFormId('Weapon', ['WEAP']),
                        ckFormId('Weapon List', ['FLST']),
                        ckFormId('Target', ['NPC_']),
                        ckFormId('Target List', ['FLST']),
                        bytes('Unknown', 4),,
                        enumS32('Target Part', ref('ActorValueEnum')),
                        enum32('VATS Action', [
                            {
                                '0': 'Unarmed Attack',
                                '1': 'One Hand Melee Attack',
                                '2': 'Two Hand Melee Attack',
                                '3': 'Magic Attack',
                                '4': 'Ranged Attack',
                                '5': 'Reload',
                                '6': 'Crouch',
                                '7': 'Stand',
                                '8': 'Switch Weapon',
                                '9': 'Toggle Weapon Drawn',
                                '10': 'Heal',
                                '11': 'Player Death',
                            }
                        ]),
                        bytes('Unknown', 4),,
                        bytes('Unknown', 4),,
                        ckFormId('Critical Effect', ['SPEL']),
                        ckFormId('Critical Effect List', ['FLST']),
                        bytes('Unknown', 4),,
                        bytes('Unknown', 4),,
                        bytes('Unknown', 4),,
                        bytes('Unknown', 4),,
                        enum32('Weapon Type', ref('WeaponAnimTypeEnum')),
                        bytes('Unknown', 4),,
                        bytes('Unknown', 4),,
                        enum32('Projectile Type', [
                            {
                                '0': 'Missile',
                                '1': 'Lobber',
                                '2': 'Beam',
                                '3': 'Flame',
                                '4': 'Cone',
                                '5': 'Barrier',
                                '6': 'Arrow',
                            }
                        ]),
                        enum32('Delivery Type', ref('TargetEnum')),
                        enum32('Casting Type', ref('CastEnum')),
                    ]),
                    ckFormId('Referenceable Object', ['NULL', 'NPC_', 'PROJ', 'TREE', 'SOUN', 'ACTI', 'DOOR', 'STAT', 'FURN', 'CONT', 'ARMO', 'AMMO', 'MISC', 'WEAP', 'BOOK', 'KEYM', 'ALCH', 'LIGH', 'GRAS', 'ASPC', 'IDLM', 'ARMA', 'MSTT', 'TACT', 'FLST', 'LVLI', 'LVSP', 'SPEL', 'SCRL', 'SHOU', 'SLGM', 'ENCH']),
                    ckFormId('Region', ['REGN']),
                    ckFormId('Keyword', ['KYWD', 'NULL']),
                    enum32('Player Action', ref('AdvanceActionEnum')),
                    enum32('Casting Type', ref('CastingSourceEnum')),
                    ckFormId('Shout', ['SHOU']),
                    ckFormId('Location', ['LCTN']),
                    ckFormId('Location Ref Type', ['LCRT']),
                    int32('Alias'),
                    uint32('Packdata ID'),
                    ckFormId('Association Type', ['ASTP']),
                    enum32('Furniture Anim', ref('FurnitureAnimTypeEnum')),
                    enum32('Furniture Entry', [
                        {
                            '0x010000': 'Front',
                            '0x020000': 'Behind',
                            '0x040000': 'Right',
                            '0x80000': 'Left',
                            '0x100000': 'Up',
                        }
                    ]),
                    ckFormId('Scene', ['NULL', 'SCEN']),
                    enum32('Ward State', ref('WardStateEnum')),
                    uint32('Event'),
                    formId('Event Data'),
                ]),
                enum32('Run On', [
                    {
                        '0': 'Subject',
                        '1': 'Target',
                        '2': 'Reference',
                        '3': 'Combat Target',
                        '4': 'Linked Reference',
                        '5': 'Quest Alias',
                        '6': 'Package Data',
                        '7': 'Event Data',
                    }
                ]),
                union('Reference', 'CTDAReferenceDecider', [
                    uint32('Unused'),
                    ckFormId('Reference', ['NULL', 'PLYR', 'ACHR', 'REFR', 'PGRE', 'PHZD', 'PMIS', 'PARW', 'PBAR', 'PBEA', 'PCON', 'PFLA']),
                ]),
                int32('Parameter #3'),
            ])),
            subrecord('CIS1', zstring('Parameter #1')),
            subrecord('CIS2', zstring('Parameter #2')),
        ]),
    );
};