let {
    addDef
} = require('../helpers');

module.exports = () => {
    addDef('EntryPointsEnum', {
        "0": "Calculate Weapon Damage",
        "1": "Calculate My Critical Hit Chance",
        "2": "Calculate My Critical Hit Damage",
        "3": "Calculate Mine Explode Chance",
        "4": "Adjust Limb Damage",
        "5": "Adjust Book Skill Points",
        "6": "Mod Recovered Health",
        "7": "Get Should Attack",
        "8": "Mod Buy Prices",
        "9": "Add Leveled List On Death",
        "10": "Get Max Carry Weight",
        "11": "Mod Addiction Chance",
        "12": "Mod Addiction Duration",
        "13": "Mod Positive Chem Duration",
        "14": "Activate",
        "15": "Ignore Running During Detection",
        "16": "Ignore Broken Lock",
        "17": "Mod Enemy Critical Hit Chance",
        "18": "Mod Sneak Attack Mult",
        "19": "Mod Max Placeable Mines",
        "20": "Mod Bow Zoom",
        "21": "Mod Recover Arrow Chance",
        "22": "Mod Skill Use",
        "23": "Mod Telekinesis Distance",
        "24": "Mod Telekinesis Damage Mult",
        "25": "Mod Telekinesis Damage",
        "26": "Mod Bashing Damage",
        "27": "Mod Power Attack Stamina",
        "28": "Mod Power Attack Damage",
        "29": "Mod Spell Magnitude",
        "30": "Mod Spell Duration",
        "31": "Mod Secondary Value Weight",
        "32": "Mod Armor Weight",
        "33": "Mod Incoming Stagger",
        "34": "Mod Target Stagger",
        "35": "Mod Attack Damage",
        "36": "Mod Incoming Damage",
        "37": "Mod Target Damage Resistance",
        "38": "Mod Spell Cost",
        "39": "Mod Percent Blocked",
        "40": "Mod Shield Deflect Arrow Chance",
        "41": "Mod Incoming Spell Magnitude",
        "42": "Mod Incoming Spell Duration",
        "43": "Mod Player Intimidation",
        "44": "Mod Player Reputation",
        "45": "Mod Favor Points",
        "46": "Mod Bribe Amount",
        "47": "Mod Detection Light",
        "48": "Mod Detection Movement",
        "49": "Mod Soul Gem Recharge",
        "50": "Set Sweep Attack",
        "51": "Apply Combat Hit Spell",
        "52": "Apply Bashing Spell",
        "53": "Apply Reanimate Spell",
        "54": "Set Boolean Graph Variable",
        "55": "Mod Spell Casting Sound Event",
        "56": "Mod Pickpocket Chance",
        "57": "Mod Detection Sneak Skill",
        "58": "Mod Falling Damage",
        "59": "Mod Lockpick Sweet Spot",
        "60": "Mod Sell Prices",
        "61": "Can Pickpocket Equipped Item",
        "62": "Mod Lockpick Level Allowed",
        "63": "Set Lockpick Starting Arc",
        "64": "Set Progression Picking",
        "65": "Make Lockpicks Unbreakable",
        "66": "Mod Alchemy Effectiveness",
        "67": "Apply Weapon Swing Spell",
        "68": "Mod Commanded Actor Limit",
        "69": "Apply Sneaking Spell",
        "70": "Mod Player Magic Slowdown",
        "71": "Mod Ward Magicka Absorption Pct",
        "72": "Mod Initial Ingredient Effects Learned",
        "73": "Purify Alchemy Ingredients",
        "74": "Filter Activation",
        "75": "Can Dual Cast Spell",
        "76": "Mod Tempering Health",
        "77": "Mod Enchantment Power",
        "78": "Mod Soul Pct Captured to Weapon",
        "79": "Mod Soul Gem Enchanting",
        "80": "Mod # Applied Enchantments Allowed",
        "81": "Set Activate Label",
        "82": "Mod Shout OK",
        "83": "Mod Poison Dose Count",
        "84": "Should Apply Placed Item",
        "85": "Mod Armor Rating",
        "86": "Mod Lockpicking Crime Chance",
        "87": "Mod Ingredients Harvested",
        "88": "Mod Spell Range (Target Loc.)",
        "89": "Mod Potions Created",
        "90": "Mod Lockpicking Key Reward Chance",
        "91": "Allow Mount Actor"
    });
};