let {
    addDef
} = require('../helpers');

module.exports = () => {
    addDef('FormTypeEnum', 
        {
            '0': 'Activator',
            '1': 'Armor',
            '2': 'Book',
            '3': 'Container',
            '4': 'Door',
            '5': 'Ingredient',
            '6': 'Light',
            '7': 'MiscItem',
            '8': 'Static',
            '9': 'Grass',
            '10': 'Tree',
            '12': 'Weapon',
            '13': 'Actor',
            '14': 'LeveledCharacter',
            '15': 'Spell',
            '16': 'Enchantment',
            '17': 'Potion',
            '18': 'LeveledItem',
            '19': 'Key',
            '20': 'Ammo',
            '21': 'Flora',
            '22': 'Furniture',
            '23': 'Sound Marker',
            '24': 'LandTexture',
            '25': 'CombatStyle',
            '26': 'LoadScreen',
            '27': 'LeveledSpell',
            '28': 'AnimObject',
            '29': 'WaterType',
            '30': 'IdleMarker',
            '31': 'EffectShader',
            '32': 'Projectile',
            '33': 'TalkingActivator',
            '34': 'Explosion',
            '35': 'TextureSet',
            '36': 'Debris',
            '37': 'MenuIcon',
            '38': 'FormList',
            '39': 'Perk',
            '40': 'BodyPartData',
            '41': 'AddOnNode',
            '42': 'MovableStatic',
            '43': 'CameraShot',
            '44': 'ImpactData',
            '45': 'ImpactDataSet',
            '46': 'Quest',
            '47': 'Package',
            '48': 'VoiceType',
            '49': 'Class',
            '50': 'Race',
            '51': 'Eyes',
            '52': 'HeadPart',
            '53': 'Faction',
            '54': 'Note',
            '55': 'Weather',
            '56': 'Climate',
            '57': 'ArmorAddon',
            '58': 'Global',
            '59': 'Imagespace',
            '60': 'Imagespace Modifier',
            '61': 'Encounter Zone',
            '62': 'Message',
            '63': 'Constructible Object',
            '64': 'Acoustic Space',
            '65': 'Ragdoll',
            '66': 'Script',
            '67': 'Magic Effect',
            '68': 'Music Type',
            '69': 'Static Collection',
            '70': 'Keyword',
            '71': 'Location',
            '72': 'Location Ref Type',
            '73': 'Footstep',
            '74': 'Footstep Set',
            '75': 'Material Type',
            '76': 'Actor Action',
            '77': 'Music Track',
            '78': 'Word of Power',
            '79': 'Shout',
            '80': 'Relationship',
            '81': 'Equip Slot',
            '82': 'Association Type',
            '83': 'Outfit',
            '84': 'Art Object',
            '85': 'Material Object',
            '87': 'Lighting Template',
            '88': 'Shader Particle Geometry',
            '89': 'Visual Effect',
            '90': 'Apparatus',
            '91': 'Movement Type',
            '92': 'Hazard',
            '93': 'SM Event Node',
            '94': 'Sound Descriptor',
            '95': 'Dual Cast Data',
            '96': 'Sound Category',
            '97': 'Soul Gem',
            '98': 'Sound Output Model',
            '99': 'Collision Layer',
            '100': 'Scroll',
            '101': 'ColorForm',
            '102': 'Reverb Parameters',
        }
    );
};