let {
    def, enumeration, uint32, conflictType, format, 
    formId, sortKey, struct, sorted, array, 
    subrecord, req, record
} = require('../helpers');

module.exports = () => {
    record('DOBJ', 'Default Object Manager', {
        members: [
            def('EDID'),
            req(subrecord('DNAM', conflictType('NormalIgnoreEmpty', sorted(array('Objects', 
                sortKey([0], struct('Object', [
                    format(conflictType('NormalIgnoreEmpty', uint32('Use')), enumeration({
                        0: 'None',
                        'AAAC': 'Action Activate',
                        'AAB1': 'Action Bleedout Start',
                        'AAB2': 'Action Bleedout Stop',
                        'AABA': 'Action Block Anticipate',
                        'AABH': 'Action Block Hit',
                        'AABI': 'Action Bumped Into',
                        'AADA': 'Action Dual Attack',
                        'AADE': 'Action Death',
                        'AADL': 'Action Dual Release',
                        'AADR': 'Action Draw',
                        'AADW': 'Action Death Wait',
                        'AAF1': 'Action Fly Start',
                        'AAF2': 'Action Fly Stop',
                        'AAFA': 'Action Fall',
                        'AAFQ': 'Action Force Equip',
                        'AAGU': 'Action Get Up',
                        'AAH1': 'Action Hover Start',
                        'AAH2': 'Action Hover Stop',
                        'AAID': 'Action Idle',
                        'AAIS': 'Action Idle Stop',
                        'AAJP': 'Action Jump',
                        'AALA': 'Action Left Attack',
                        'AALD': 'Action Left Ready',
                        'AALI': 'Action Left Interrupt',
                        'AALK': 'Action Look',
                        'AALM': 'Action Large Movement Delta',
                        'AALN': 'Action Land',
                        'AALR': 'Action Left Release',
                        'AALS': 'Action Left Sync Attack',
                        'AAMT': 'Action Mantle',
                        'AAOE': 'Action AoE Attack',
                        'AAPA': 'Action Right Power Attack',
                        'AAPE': 'Action Path End',
                        'AAPS': 'Action Path Start',
                        'AAR2': 'Action Large Recoil',
                        'AARA': 'Action Right Attack',
                        'AARC': 'Action Recoil',
                        'AARD': 'Action Right Ready',
                        'AARI': 'Action Right Interrupt',
                        'AARR': 'Action Right Release',
                        'AARS': 'Action Right Sync Attack',
                        'AAS1': 'Action Stagger Start',
                        'AASC': 'Action Shield Change',
                        'AASH': 'Action Sheath',
                        'AASN': 'Action Sneak',
                        'AASP': 'Action Sprint Stop',
                        'AASS': 'Action Summoned Start',
                        'AAST': 'Action Sprint Start',
                        'AASW': 'Action Swim State Change',
                        'AAVC': 'Action Voice',
                        'AAVD': 'Action Voice Ready',
                        'AAVI': 'Action Voice Interrupt',
                        'AAVR': 'Action Voice Release',
                        'AAWH': 'Action Ward Hit',
                        'ABLA': 'Action Begin Looping Activate',
                        'ABOL': 'Action Bolt Charge',
                        'ABSE': 'Art Object Absorb Effect',
                        'ACHI': 'Action Hide',
                        'ACSS': 'Action Cover Sprint Start',
                        'ACTN': 'Action Tunnel',
                        'ACWR': 'Action Cower',
                        'ADGE': 'Action Dodge',
                        'ADPA': 'Action Dual Power Attack',
                        'AECL': 'Action Enter Cover',
                        'AELA': 'Action End Looping Activate',
                        'AENC': 'Action Enter Combat',
                        'AENI': 'Action Dialogue Enter',
                        'AEVD': 'Action Evade',
                        'AEXC': 'Action Exit Cover',
                        'AEXI': 'Action Dialogue Exit',
                        'AEXT': 'Action Exit Combat',
                        'AFCH': 'Action Fire Charge',
                        'AFCO': 'Action Fire Charge Hold',
                        'AFEM': 'Action Fire Empty',
                        'AFIA': 'Action Fire Auto',
                        'AFIS': 'Action Fire Single',
                        'AFLT': 'Action Flip-Throw',
                        'AFNP': 'Keyword Activator Furniture No Player',
                        'AGAL': 'Action Gun Alert',
                        'AGCS': 'Action Gun Charge Start',
                        'AGDN': 'Action Gun Down',
                        'AGRX': 'Action Gun Relaxed',
                        'AGRY': 'Action Gun Ready',
                        'AIDW': 'Action Idle Warn',
                        'AIEN': 'Action Interaction Enter',
                        'AIEQ': 'Action Interaction Exit Quick',
                        'AIEX': 'Action Interaction Exit',
                        'AILN': 'Action Dialogue Listen Negative',
                        'AILp': 'Action Dialogue Listen Positive',
                        'AILQ': 'Action Dialogue Listen Question',
                        'AINT': 'Action Intimidate',
                        'AIVC': 'Verlet Cape',
                        'AIXA': 'Action Interaction Exit Alternate',
                        'AKDN': 'Action Knockdown',
                        'ALIC': 'Action Limb Critical',
                        'ALIK': 'Alcohol Item keyword',
                        'ALPA': 'Action Left Power Attack',
                        'ALTI': 'Action Dialogue Listen',
                        'AMBK': 'Action Move Backward',
                        'AMEL': 'Action Melee',
                        'AMFD': 'Action Move Forward',
                        'AMLT': 'Action Move Left',
                        'AMRT': 'Action Move Right',
                        'AMSP': 'Action Move Stop',
                        'AMST': 'Action Move Start',
                        'ANML': 'Keyword Animal',
                        'ANSC': 'Action NonSupport Contact',
                        'AODA': 'Keyword Armor Material Daedric',
                        'AODB': 'Keyword Armor Material Dragonbone',
                        'AODP': 'Keyword Armor Material Dragonplate',
                        'AODS': 'Keyword Armor Material Dragonscale',
                        'AODW': 'Keyword Armor Material Dwarven',
                        'AOEB': 'Keyword Armor Material Ebony',
                        'AOEL': 'Keyword Armor Material Elven',
                        'AOES': 'Keyword Armor Material ElvenSplinted',
                        'AOFE': 'Keyword Armor Material Iron',
                        'AOFL': 'Keyword Armor Material FullLeather',
                        'AOGL': 'Keyword Armor Material Glass',
                        'AOHI': 'Keyword Armor Material Hide',
                        'AOIB': 'Keyword Armor Material IronBanded',
                        'AOIH': 'Keyword Armor Material ImperialHeavy',
                        'AOIM': 'Keyword Armor Material Imperial',
                        'AOIR': 'Keyword Armor Material ImperialReinforced',
                        'AOOR': 'Keyword Armor Material Orcish',
                        'AOSC': 'Keyword Armor Material Scaled',
                        'AOSD': 'Keyword Armor Material Studded',
                        'AOSK': 'Keyword Armor Material Stormcloak',
                        'AOSP': 'Keyword Armor Material SteelPlate',
                        'AOST': 'Keyword Armor Material Steel',
                        'APIC': 'Action Pipboy Close',
                        'APID': 'Action Pipboy Data',
                        'APII': 'Action Pipboy Inventory',
                        'APIM': 'Action Pipboy Map',
                        'APIN': 'Action Pipboy Inspect',
                        'APIP': 'Action Pipboy',
                        'APIS': 'Action Pipboy Stats',
                        'APIT': 'Action Pipboy Tab',
                        'APIZ': 'Action Pipboy Zoom',
                        'APLH': 'Action Pipboy Load Holotape',
                        'APLN': 'Action Dialogue Listen Neutral',
                        'APNC': 'Action Panic',
                        'APPS': 'Action Pipboy Select',
                        'APR0': 'Action Pipboy Radio Off',
                        'APR1': 'Action Pipboy Radio On',
                        'APSH': 'Allow Player Shout',
                        'APTP': 'Action Pipboy Tab Previous',
                        'AREL': 'Action Reload',
                        'ARGI': 'Action Ragdoll Instant',
                        'ARTL': 'Armor Material List',
                        'ASFL': 'Action Shuffle',
                        'ASID': 'Action Idle Stop Instant',
                        'ASIR': 'Action Sighted Release',
                        'ASIT': 'Action Sighted',
                        'ATHR': 'Action Throw',
                        'ATKI': 'Action Dialogue Talking',
                        'ATLE': 'Action Turn Left',
                        'ATRI': 'Action Turn Right',
                        'ATSP': 'Action Turn Stop',
                        'AVVP': 'Vampire Available Perks',
                        'AVWP': 'Unused',
                        'AWWS': 'Action Waterwalk Start',
                        'AWWW': 'Bunny Faction',
                        'BAPO': 'Base Potion',
                        'BAPS': 'Base Poison',
                        'BEEP': 'Keyword Robot',
                        'BENA': 'Base Armor Enchantment',
                        'BENW': 'Base Weapon Enchantment',
                        'BTMS': 'Battle Music',
                        'CACA': 'Commanded Actor Ability',
                        'CHIK': 'Chem Item keyword',
                        'CLIK': 'Clothes Item keyword',
                        'CMPX': 'Complex Scene Object',
                        'CNMK': 'Keyword nullptr Mod',
                        'COEX': 'Keyword Conditional Explosion',
                        'COOK': 'Keyword Cooking Pot',
                        'CSTY': 'Combat Style',
                        'CWNE': 'Keyword Civil War Neutral',
                        'CWOK': 'Keyword Civil War Owner',
                        'DAED': 'Keyword Daedra',
                        'DBHF': 'Dark Brotherhood Faction',
                        'DCMS': 'Dungeon Cleared Music',
                        'DCZM': 'Dragon Crash Zone Marker',
                        'DDSC': 'Dialogue Voice Category',
                        'DEIS': 'Drug Wears Off Image Space',
                        'DFTS': 'Footstep Set',
                        'DGFL': 'DialogueFollower Quest',
                        'DIEN': 'Keyword Disallow Enchanting',
                        'DLMT': 'Landscape Material',
                        'DLZM': 'Dragon Land Zone Marker',
                        'DMFL': 'Default Movement Type: Fly',
                        'DMSN': 'Default Movement Type: Sneak',
                        'DMSW': 'Default Movement Type: Swim',
                        'DMWL': 'Default Movement Type: Default',
                        'DOP2': 'Dialogue Output Model 3D',
                        'DOP3': 'Dialogue Output Model 2D',
                        'DRAK': 'Keyword Dragon',
                        'DTMS': 'Death Music',
                        'EACA': 'Every Actor Ability',
                        'EPDF': 'Eat Package Default Food',
                        'FFFP': 'Keyword Furniture Forces 1st Person',
                        'FFTP': 'Keyword Furniture Forces 3rd Person',
                        'FOIK': 'Food Item Keyword',
                        'FORG': 'Keyword Forge',
                        'FTEL': 'Male Face Texture Set: Eyes',
                        'FTGF': 'Fighters\' Guild Faction',
                        'FTHD': 'Male Face Texture Set: Head',
                        'FTHF': 'Female Face Texture Set: Head',
                        'FTMF': 'Female Face Texture Set: Mouth',
                        'FTML': 'Favor travel marker location',
                        'FTMO': 'Male Face Texture Set: Mouth',
                        'FTNP': 'Furniture Test NPC',
                        'FTRF': 'Female Face Texture Set: Eyes',
                        'GCK1': 'Keyword Generic Craftable Keyword 01',
                        'GCK2': 'Keyword Generic Craftable Keyword 02',
                        'GCK3': 'Keyword Generic Craftable Keyword 03',
                        'GCK4': 'Keyword Generic Craftable Keyword 04',
                        'GCK5': 'Keyword Generic Craftable Keyword 05',
                        'GCK6': 'Keyword Generic Craftable Keyword 06',
                        'GCK7': 'Keyword Generic Craftable Keyword 07',
                        'GCK8': 'Keyword Generic Craftable Keyword 08',
                        'GCK9': 'Keyword Generic Craftable Keyword 09',
                        'GCKX': 'Keyword Generic Craftable Keyword 10',
                        'GFAC': 'Guard Faction',
                        'GLIK': 'Gloves Item Keyword',
                        'GOLD': 'Gold',
                        'GRIK': 'Grenade Item Keyword',
                        'HBAL': 'Help Basic Alchemy',
                        'HBBR': 'Help Barter',
                        'HBCO': 'Help Basic Cooking',
                        'HBEC': 'Help Basic Enchanting',
                        'HBFG': 'Help Basic Forging',
                        'HBFS': 'Help Favorites',
                        'HBFT': 'Help Teamate Favor',
                        'HBHJ': 'Help Jail',
                        'HBJL': 'Help Journal',
                        'HBLH': 'Help Low Health',
                        'HBLK': 'Help Basic Lockpicking PC',
                        'HBLM': 'Help Low Magicka',
                        'HBLS': 'Help Low Stamina',
                        'HBLU': 'Help Leveling up',
                        'HBLX': 'Help Basic Lockpicking Console',
                        'HBML': 'Help Basic Smelting',
                        'HBMM': 'Help Map Menu',
                        'HBOC': 'Help Basic Object Creation',
                        'HBSA': 'Help Basic Smithing Armor',
                        'HBSK': 'Help Skills Menu',
                        'HBSM': 'Help Basic Smithing Weapon',
                        'HBTA': 'Help Basic Tanning',
                        'HBWC': 'Help Weapon Charge',
                        'HCLL': 'FormList Hair Color List',
                        'HEIK': 'Helmet Item Keyword',
                        'HFSD': 'Heartbeat Sound Fast',
                        'HMPC': 'Help Manual PC',
                        'HMXB': 'Help Manual XBox',
                        'HRSK': 'Keyword Horse',
                        'HSSD': 'Heartbeat Sound Slow',
                        'HVFS': 'Harvest Failed Sound',
                        'HVSS': 'Harvest Sound',
                        'HWIK': 'Heavy Weapon Item keyword',
                        'IMDI': 'Dialogue Imagespace',
                        'IMID': 'ImageSpaceModifier for inventory menu.',
                        'IMLH': 'Imagespace: Low Health',
                        'IMPP': 'ImageSpaceModifier for Pipboy menu in Power armor.',
                        'IOPM': 'Interface Output Model',
                        'JRLF': 'Jarl Faction',
                        'JWLR': 'Keyword Jewelry',
                        'KHFL': 'Kinect Help FormList',
                        'KTRW': 'Teammate Ready Weapon',
                        'KWBR': 'Color Form',
                        'KWCU': 'Keyword Cuirass',
                        'KWDM': 'Keyword DummyObject',
                        'KWDO': 'Keyword ClearableLocation',
                        'KWGE': 'Keyword UseGeometryEmitter',
                        'KWMS': 'Keyword MustStop',
                        'LGH1': 'Default Light 1',
                        'LGH2': 'Default Light 2',
                        'LGH3': 'Default Light 3',
                        'LGH4': 'Default Light 4',
                        'LGHP': 'Pipboy Light',
                        'LKHO': 'Keyword Hold Location',
                        'LKPK': 'Lockpick',
                        'LMHP': 'Local Map Hide Plane',
                        'LRRD': 'LocRefType Resource Destructible',
                        'LRSO': 'LocRefType Civil War Soldier',
                        'LSIS': 'Imagespace: Load screen',
                        'MBIK': 'Med Bag Item Keyword',
                        'MDSC': 'Music Sound Category',
                        'MFSN': 'Magic Fail Sound',
                        'MGGF': 'Mages\' Guild Faction',
                        'MIIK': 'Mine Item Keyword',
                        'MMCL': 'Main Menu Cell',
                        'MMSD': 'Map Menu Looping Sound',
                        'MNTK': 'Keyword Mount',
                        'MTSC': 'Master Sound Category',
                        'MVBL': 'Keyword Movable',
                        'NASD': 'No-Activation Sound',
                        'NDSC': 'Non-Dialogue Voice Category',
                        'NMRD': 'Road Marker',
                        'NPCK': 'Keyword NPC',
                        'NRNT': 'Keyword Nirnroot',
                        'P3OM': 'Player\'s Output Model 3rd Person',
                        'PDLC': 'Pause During Loading Menu Category',
                        'PDMC': 'Pause During Menu Category Fade',
                        'PDSA': 'Putdown Sound Armor',
                        'PDSB': 'Putdown Sound Book',
                        'PDSG': 'Putdown Sound Generic',
                        'PDSI': 'Putdown Sound Ingredient',
                        'PDSW': 'Putdown Sound Weapon',
                        'PFAC': 'Player Faction',
                        'PIMC': 'Pause During Menu Category Immediate',
                        'PIVV': 'Player Is Vampire Variable',
                        'PIWV': 'UNUSED01',
                        'PLOC': 'PersistAll Location',
                        'PLST': 'Default Pack List',
                        'POEQ': 'Potion Equip',
                        'POPM': 'Player\'s Output Model 1st Person',
                        'PTEM': 'Package Template',
                        'PTFR': 'PotentialFollower Faction',
                        'PTNP': 'Pathing Test NPC',
                        'PUSA': 'Pickup Sound Armor',
                        'PUSB': 'Pickup Sound Book',
                        'PUSG': 'Pickup Sound Generic',
                        'PUSI': 'Pickup Sound Ingredient',
                        'PUSW': 'Pickup Sound Weapon',
                        'PVFA': 'Player Voice Female',
                        'PVFC': 'Player Voice Female Child',
                        'PVMA': 'Player Voice Male',
                        'PVMC': 'Player Voice Male Child',
                        'PWFD': 'Wait-For-Dialogue Package',
                        'QMEA': 'Quest Marker Enemy Above',
                        'QMEB': 'Quest Marker Enemy Below',
                        'QMEN': 'Quest Marker Enemy',
                        'QMFO': 'Quest Marker Follower',
                        'QMLO': 'Quest Marker Location',
                        'RIVR': 'Vampire Race',
                        'RIVS': 'Vampire Spells',
                        'RIWR': 'UNUSED02',
                        'RKIK': 'Repair Kit Item Keyword',
                        'RUSG': 'Keyword Reusable SoulGem',
                        'RVBT': 'Reverb Type',
                        'SALT': 'Sitting Angle Limit',
                        'SAT1': 'Keyword Scale Actor To 1.0',
                        'SCSD': 'Soul Captured Sound',
                        'SFDC': 'SFX To Fade In Dialogue Category',
                        'SFSN': 'Shout Fail Sound',
                        'SKLK': 'Skeleton Key',
                        'SLDM': 'Snow LOD Material',
                        'SLHD': 'Snow LOD Material HD',
                        'SMLT': 'Keyword Smelter',
                        'SMSC': 'Stats Mute Category',
                        'SPFK': 'Keyword Special Furniture',
                        'SSSC': 'Stats Music',
                        'TANN': 'Keyword Tanning Rack',
                        'TKAM': 'Keyword Type Ammo',
                        'TKAR': 'Keyword Type Armor',
                        'TKBK': 'Keyword Type Book',
                        'TKGS': 'Telekinesis Grab Sound',
                        'TKIG': 'Keyword Type Ingredient',
                        'TKKY': 'Keyword Type Key',
                        'TKMS': 'Keyword Type Misc',
                        'TKPT': 'Keyword Type Potion',
                        'TKSG': 'Keyword Type SoulGem',
                        'TKTS': 'Telekinesis Throw Sound',
                        'TKWP': 'Keyword Type Weapon',
                        'TVGF': 'Thieves\' Guild Faction',
                        'UNDK': 'Keyword Undead',
                        'URVT': 'Underwater Reverb Type',
                        'UWLS': 'Underwater Loop Sound',
                        'VAMP': 'Keyword Vampire',
                        'VLOC': 'Virtual Location',
                        'VOEQ': 'Voice Equip',
                        'WASN': 'Ward Absorb Sound',
                        'WBSN': 'Ward Break Sound',
                        'WDSN': 'Ward Deflect Sound',
                        'WEML': 'Weapon Material List',
                        'WMDA': 'Keyword Weapon Material Daedric',
                        'WMDH': 'Keyword Weapon Material DraugrHoned',
                        'WMDR': 'Keyword Weapon Material Draugr',
                        'WMDW': 'Keyword Weapon Material Dwarven',
                        'WMEB': 'Keyword Weapon Material Ebony',
                        'WMEL': 'Keyword Weapon Material Elven',
                        'WMFA': 'Keyword Weapon Material Falmer',
                        'WMFH': 'Keyword Weapon Material FalmerHoned',
                        'WMGL': 'Keyword Weapon Material Glass',
                        'WMIK': 'Workshop Misc Item Keyword',
                        'WMIM': 'Keyword Weapon Material Imperial',
                        'WMIR': 'Keyword Weapon Material Iron',
                        'WMOR': 'Keyword Weapon Material Orcish',
                        'WMST': 'Keyword Weapon Material Steel',
                        'WMWE': 'World Map Weather',
                        'WMWO': 'Keyword Weapon Material Wood',
                        'WPOK': 'Workshop Player Ownership',
                        'WTBA': 'Keyword WeaponTypeBoundArrow',
                        'WWSP': 'UNUSED03'
                    })),
                    conflictType('NormalIgnoreEmpty', formId('Object ID'))
                ]))
            )))))
        ]
    })
};