let {
    addDef, enumeration
} = require('../helpers');

module.exports = () => {
    addDef('EntryPointsEnum', 
        enumeration({
            0: 'Mod Breath Timer',
            1: 'Mod My Critical Hit Chance',
            2: 'Mod My Critical Hit Damage Mult',
            3: 'Mod Mine Explode Chance',
            4: 'Mod Incoming Limb Damage',
            5: 'Mod Book Actor Value Bonus',
            6: 'Mod Recovered Health',
            7: 'Set Should Attack',
            8: 'Mod Buy Prices',
            9: 'Add Leveled List On Death',
            10: 'Set Max Carry Weight',
            11: 'Mod Addiction Chance',
            12: 'Mod Addiction Duration',
            13: 'Mod Positive Chem Duration',
            14: 'Activate',
            15: 'Ignore Running During Detection',
            16: 'Ignore Broken Lock',
            17: 'Mod Enemy Critical Hit Chance',
            18: 'Mod Sneak Attack Mult',
            19: 'Mod Max Placeable Mines',
            20: 'Mod Bow Zoom',
            21: 'Mod Recover Arrow Chance',
            22: 'Mod Exp',
            23: 'Mod Telekinesis Distance',
            24: 'Mod Telekinesis Damage Mult',
            25: 'Mod Telekinesis Damage',
            26: 'Mod Bashing Damage',
            27: 'Mod Power Attack Action Points',
            28: 'Mod Power Attack Damage',
            29: 'Mod Spell Magnitude',
            30: 'Mod Spell Duration',
            31: 'Mod Secondary Value Weight',
            32: 'Mod Armor Weight',
            33: 'Mod Incoming Stagger',
            34: 'Mod Target Stagger',
            35: 'Mod Weapon Attack Damage',
            36: 'Mod Incoming Weapon Damage',
            37: 'Mod Target Damage Resistance',
            38: 'Mod Spell Cost',
            39: 'Mod Percent Blocked',
            40: 'Mod Shield Deflect Arrow Chance',
            41: 'Mod Incoming Spell Magnitude',
            42: 'Mod Incoming Spell Duration',
            43: 'Mod Player Intimidation',
            44: 'Mod Ricochet Chance',
            45: 'Mod Ricochet Damage',
            46: 'Mod Bribe Amount',
            47: 'Mod Detection Light',
            48: 'Mod Detection Movement',
            49: 'Mod Scrap Reward Mult',
            50: 'Set Sweep Attack',
            51: 'Apply Combat Hit Spell',
            52: 'Apply Bashing Spell',
            53: 'Apply Reanimate Spell',
            54: 'Set Boolean Graph Variable',
            55: 'Mod Spell Casting Sound Event',
            56: 'Mod Pickpocket Chance',
            57: 'Mod Detection Sneak Skill',
            58: 'Mod Falling Damage',
            59: 'Mod Lockpick Sweet Spot',
            60: 'Mod Sell Prices',
            61: 'Set Pickpocket Equipped Item',
            62: 'Set Player Gate Lockpick',
            63: 'Set Lockpick Starting Arc',
            64: 'Set Progression Picking',
            65: 'Set Lockpicks Unbreakable',
            66: 'Mod Alchemy Effectiveness',
            67: 'Apply Weapon Swing Spell',
            68: 'Mod Commanded Actor Limit',
            69: 'Apply Sneaking Spell',
            70: 'Mod Player Magic Slowdown',
            71: 'Mod Ward Magicka Absorption Pct',
            72: 'Mod Initial Ingredient Effects Learned',
            73: 'Purify Alchemy Ingredients',
            74: 'Set Filter Activation',
            75: 'Set Dual Cast',
            76: 'Mod Outgoing Explosion Limb Damage',
            77: 'Mod Enchantment Power',
            78: 'Mod Soul Pct Captured to Weapon',
            79: 'Mod VATS Attack Action Points',
            80: 'Mod Reflect Damage Chance',
            81: 'Set Activate Label',
            82: 'Mod Kill Experience',
            83: 'Mod Poison Dose Count',
            84: 'Set Apply Placed Item',
            85: 'Mod Armor Rating',
            86: 'Mod lockpicking crime chance',
            87: 'Mod ingredients harvested',
            88: 'Mod Spell Range (Target Loc.)',
            89: 'Mod Critical Charge Mult on Ricochet',
            90: 'Mod lockpicking key reward chance',
            91: 'Mod Auto Lockpicking Chance',
            92: 'Mod Auto Hacking Chance',
            93: 'Mod Typed Weapon Attack Damage',
            94: 'Mod Typed Incoming Weapon Damage',
            95: 'Mod Charisma Challenge Chance',
            96: 'Mod Sprint AP Drain Rate',
            97: 'Mod Drawn Weapon Weight Speed Effect',
            98: 'Set Player Gate Hacking',
            99: 'Mod Player Explosion Damage',
            100: 'Mod Player Explosion Scale',
            101: 'Set Rads To Health Mult',
            102: 'Mod Actor Scope Stability',
            103: 'Mod Actor Grenade Speed Mult',
            104: 'Mod Explosion Force',
            105: 'Mod VATS Penetration Min Visibility',
            106: 'Mod Rads for Rad Health Max',
            107: 'Mod VATS Player AP On Kill Chance',
            108: 'Set VATS Fill Critical Bar On Hit',
            109: 'Mod VATS Concentrated Fire Chance Bonus',
            110: 'Mod VATS Critical Count',
            111: 'Mod VATS Hold Em Steady Bonus',
            112: 'Mod Typed Spell Magnitude',
            113: 'Mod Typed Incoming Spell Magnitude',
            114: 'Set VATS Gun-Fu Num Targets For Crits',
            115: 'Mod Outgoing Limb Damage',
            116: 'Mod Restore Action Cost Value',
            117: 'Mod VATS Reload Action Points',
            118: 'Mod Incoming Battery Damage',
            119: 'Mod VATS Critical Charge',
            120: 'Mod Exp Location',
            121: 'Mod Exp Speech',
            122: 'Mod VATS Head Shot Chance',
            123: 'Mod VATS Hit Chance',
            124: 'Mod Incoming Explosion Damage',
            125: 'Mod Ammo Health Mult',
            126: 'Mod Hacking Guesses',
            127: 'Mod Terminal Lockout Time',
            128: 'Set Undetectable',
            129: 'Invest In Vendor',
            130: 'Mod Outgoing Limb Bash Damage',
            131: 'Set Run While Over Encumbered',
            132: 'Get Component Radar Distance',
            133: 'Show Grenade Trajectory',
            134: 'Mod Cone-of-fire Mult',
            135: 'Mod VATS Concentrated Fire Damage Mult',
            136: 'Apply Bloody Mess Spell',
            137: 'Mod VATS Critical Fill Chance On Bank',
            138: 'Mod VATS Critical Fill Chance On Use',
            139: 'Set VATS Critical Fill On AP Reward',
            140: 'Set VATS Critical Fill On Stranger',
            141: 'Mod Gun Range Mult',
            142: 'Mod Scope Hold Breath AP Drain Mult',
            143: 'Set Force Decapitate',
            144: 'Mod VATS Shoot Explosive Damage Mult',
            145: 'Mod Scrounger Fill Ammo Chance',
            146: 'Set Can Explode Pants',
            147: 'Set VATS Penetration Full Damage',
            148: 'Mod VATS Gun-Fu 2nd Target Dmg Mult',
            149: 'Mod VATS Gun-Fu 3rd Target Dmg Mult',
            150: 'Mod VATS Gun-Fu 4th+ Target Dmg Mult',
            151: 'Mod VATS Blitz Max Distance',
            152: 'Set VATS Blitz Max Dmg Mult',
            153: 'Mod VATS Blitz Dmg Bonus Dist',
            154: 'Mod Bash Critical Chance',
            155: 'VATS Apply Paralyzing Palm Spell',
            156: 'Mod Fatigue for Fatigue AP Max',
            157: 'Set Fatigue to AP Mult'
        })
    );
};